### ISSUE TITLE
Hash mismatch when order is different in an array of objects

### ISSUE THREAD

**Issue by jpenaroche** [oyamist/merkle-json#8] opened 2023-08-10 10:56 UTC
```javascript 
const { MerkleJson } = require('merkle-json')
const mj = new MerkleJson()
console.log(mj.hash([
	{
		a:1,
		b:2
	},
	{
		c:3,
		d:4
	}
])) 
console.log(mj.hash([
	{
		c:3,
		d:4
	},
	{
		a:1,
		b:2,
	}
])) 

//Output
//First Hash
f888104fdfad4268bbecd85b7baeb28b

//Second Hash
b3eaa8376e37fc432264ecfb150ebe2d
```

**Comment by firepick1** [comment] 2023-08-19 12:04
Hi!  I think that's actually by design. The hash is computed from the serialized JSON, so array order does matter. If you wanted different semantics, it might be best to fork the repo and have your fork sort all arrays before serialization. An alternate implementation might be for you to use objects instead of array because Object keys *are* sorted.  Object keys are sorted because Javascript key order is semantically undefined for Object.

I'm inclined to close this issue if that's all right.

**Closed as completed** 2023-10-18 16:14 UTC
